---
- name: create service config
  template:
    src: 'service'
    dest: '/etc/systemd/system/{{ api_service_name }}.service'
    backup: yes
  notify: reload systemd (api)

- name: enable service
  service:
    name: '{{ api_service_name }}'
    enabled: yes

- name: start service
  service:
    name: '{{ api_service_name }}'
    state: started
