---
- name: check if swap file exists
  stat:
    path: "{{ swap_file_dest }}"
  register: swap_file_check

- when: not swap_file_check.stat.exists
  block:
    - name: create swap file
      command: 'fallocate -l {{ swap_file_size }} {{ swap_file_dest }}'

    - name: set permissions for swap file
      file:
        path: '{{ swap_file_dest }}'
        mode: 0600

    - name: format the file as swap
      command: 'mkswap {{ swap_file_dest }}'

    - name: enable use swap file
      command: 'swapon {{ swap_file_dest }}'

    - name: enable swap file at bootup
      lineinfile:
        path: /etc/fstab
        regexp: '{{ swap_file_dest }}'
        line: '{{ swap_file_dest }} swap swap defaults 0 0'
