---
- name: remove default config
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: unlink default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
