---
- name: postfix configuration mailer type in debconf
  debconf:
    name: 'postfix'
    question: 'postfix/main_mailer_type'
    vtype: 'select'
    value: 'Internet Site'

- name: postfix configuration mailname in debconf
  debconf:
    name: 'postfix'
    question: 'postfix/mailname'
    vtype: 'string'
    value: '{{ postfix_mailname }}'

- name: install postfix
  apt:
    name: postfix

- name: start postfix
  service:
    name: 'postfix'
    state: started

- name: change 'myhostname' variable
  lineinfile:
    dest: '/etc/postfix/main.cf'
    regexp: '^myhostname ='
    line: 'myhostname = {{ postfix_mailname }}'
    backup: yes
  notify: reload postfix

