---
- name: apt-get update
  apt:
    update_cache: yes

- name: install unattended-upgrades
  apt:
    name: unattended-upgrades

- name: install htop
  apt:
    name: htop

- name: install mc
  apt:
    name: mc
