---
- name: add apt key
  apt_key:
    url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    state: present

- name: add apt repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main'
    filename: pgdg
    state: present

- name: install postgresql
  apt:
    name: '{{ postgres_version }}'
