---
- name: Test
  hosts: test
  roles:
    - common
    - role: firewall
      when: env_type == 'prod'
    - swap
    - java
    - role: api
      vars:
        api_service_name: 'test-service'
        api_service_description: 'Test Service'
    - nginx
#    - compiled-nginx
    - role: letsencrypt
      vars:
        letsencrypt_domains:
          - '{{ dns_name }}'
      when: env_type == 'prod'
    - role: api-nginx
      vars:
        api_port: '9002'
        config_name: 'test.nginx'
        remote_config_name: 'test'
    - role: postgres
      vars:
        db_user_name: test
        db_user_password: '{{ lookup("file", "../inventories/{{ env_type }}/postgres.passwd") }}'
        db_name: test_db
    - role: postfix
      when: env_type == 'prod'
    - role: zabbix-agent
      vars:
        postgres_zabbix_user_password: '{{ lookup("file", "../inventories/{{ env_type }}/zabbix.passwd") }}'
