---
- name: configure "pcre" module
  command: '{{ item }}'
  with_items:
    - './configure'
    - 'make'
    - 'make install'
  args:
    chdir: '/tmp/pcre-{{ pcre_version }}'

- name: configure "zlib" module
  command: '{{ item }}'
  with_items:
    - './configure'
    - 'make'
    - 'make install'
  args:
    chdir: '/tmp/zlib-{{ zlib_version }}'

- name: configure "openssl" module
  command: '{{ item }}'
  with_items:
    - './Configure linux-x86_64 --prefix=/usr'
    - 'make'
    - 'make install'
  args:
    chdir: '/tmp/openssl-{{ openssl_version }}'

- name: configure "nginx"
  command: '{{ item }}'
  with_items:
    - "./configure \
        --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-DhOtPd/nginx-{{ nginx_version }}=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' \
        --with-ld-opt='-Wl,-z,relro -Wl,-z,now' \
        --sbin-path=/usr/sbin/nginx \
        --prefix=/usr/share/nginx \
        --conf-path=/etc/nginx/nginx.conf \
        --http-log-path=/var/log/nginx/access.log \
        --error-log-path=/var/log/nginx/error.log \
        --lock-path=/var/lock/nginx.lock \
        --pid-path=/run/nginx.pid \
        --modules-path=/usr/lib/nginx/modules \
        --http-client-body-temp-path=/var/lib/nginx/body \
        --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
        --http-proxy-temp-path=/var/lib/nginx/proxy \
        --http-scgi-temp-path=/var/lib/nginx/scgi \
        --http-uwsgi-temp-path=/var/lib/nginx/uwsgi\
        --with-debug \
        --with-pcre-jit \
        --with-http_ssl_module \
        --with-http_stub_status_module \
        --with-http_realip_module \
        --with-http_auth_request_module \
        --with-http_v2_module \
        --with-http_dav_module \
        --with-http_slice_module \
        --with-threads \
        --with-http_addition_module \
        --with-http_gunzip_module \
        --with-http_gzip_static_module \
        --with-http_image_filter_module=dynamic \
        --with-http_sub_module \
        --with-http_xslt_module=dynamic \
        --with-stream=dynamic \
        --with-stream_ssl_module \
        --with-mail=dynamic \
        --with-mail_ssl_module \
        --with-stream_ssl_preread_module \
        --with-openssl=/tmp/openssl-{{ openssl_version }} \
        --with-pcre=/tmp/pcre-{{ pcre_version }} \
        --with-zlib=/tmp/zlib-{{ zlib_version }} \
        --add-module=/tmp/nginx-upload-module-master \
        --add-module=/tmp/echo-nginx-module-{{ echo_nginx_version }} \
        --add-module=/tmp/ngx_http_substitutions_filter_module-{{ ngx_http_substitutions_filter_version }} \
        --add-module=/tmp/nginx-dav-ext-module-{{ dav_ext_version }}"
    - 'make'
    - 'make install'
  args:
    chdir: '/tmp/nginx-{{ nginx_version }}'
